- name: variables from files
  hosts: web
  vars:
    NAME: "Neelima"
    COURSE: "Ansible"
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "Hi, This is {{NAME}} and i am learning {{COURSE}}"