- name: check a number is less than 10 or not
  hosts: local
  connection: local
  vars:
    my_number: 140
  tasks:
  - name: print this if number is less than 10
    ansible.builtin.debug:
      msg: "The number {{ my_number }} is less than 10"
    when: number  < 10 #conditional expression
  - name: print this when number is greater than or equal to 10
    ansible.builtin.debug:
      msg : "The number {{ my_number }} is greater than 10"
    when: my_number >= 10