- name: create user
  hosts: web
  become: yes
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense
    register: USER #here USER is a variable that gets the output from above command.
    ignore_errors: True

  - name: Print the user information
    ansible.builtin.debug:
      msg : "User info : {{ USER }}"

  - name: Create user
    ansible.builtin.command: useradd expense
    when: USER.rc != 0